version: "3.9"

services:
  tracker:
    container_name: location-tracker
    image: dpimkin/location-tracker:1.0.0
    links:
      - tracker_redis:app_db
    ports:
      - '8088:8088'
    restart: always
    depends_on:
      - tracker_redis

  tracker_redis:
    container_name: location-tracker-redis
    image: redis:5.0.3-alpine
    ports:
      - '6379:6379'
    restart: always

  delivery_fleet:
    container_name: delivery-fleet
    image: dpimkin/delivery-fleet:1.0.0
    links:
      - delivery_fleet_db:app_db
    ports:
      - '8080:8080'
    restart: always
    depends_on:
      - delivery_fleet_db
      - tracker


  delivery_fleet_db:
    container_name: delivery-fleet-db
    image: mongo:5.0.14
    ports:
      - '8080:8080'


